bookmarks = [
    {label = "Projects", mount = "/home/edward/Projects"},
    {label = "Torrents", mount = "/home/edward/Torrents"},
    {label = "Certificates", mount = "/home/edward/Certificates"},
]

[theme]
bg = "#0C0C0C"
fg = "#fafafa"
success = "#16a34a"
danger = "#dc2626"
